In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/iitm21f1002300/indic-lingua-data/val.jsonl
/kaggle/input/datasets/iitm21f1002300/indic-lingua-data/test.jsonl
/kaggle/input/datasets/iitm21f1002300/indic-lingua-data/train.jsonl

# Indic LLMLingua-2 Training — Optuna Hyperparameter Tuning

This notebook fine-tunes the LLMLingua-2 token classification model on an extended Indic dataset
(the original LLMLingua-2 dataset + additional XL-Sum supervision).

**Task:** binary token classification — each token is classified as `KEEP (1)` or `REMOVE (0)` during
prompt/context compression.

**Pipeline**
1. Load & inspect the dataset
2. Tokenize and align word-level labels to subword tokens
3. Define the compute-metrics function
4. Run an **Optuna** hyperparameter search (with real mid-training pruning)
5. Retrieve the best trial's hyperparameters
6. Re-train a final model end-to-end with those hyperparameters
7. Evaluate the final model on the **validation set** and save all artifacts

> Dataset used previously: 1,609 train / 201 validation / 202 test examples, class balance
> ≈ 78% REMOVE vs 22% KEEP tokens (523,634 vs 143,011). Base model: `FacebookAI/xlm-roberta-base`
> (~277M parameters).

## 1. Setup & Environment

In [2]:
!pip install -q optuna evaluate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 2.7 MB/s eta 0:00:00

In [3]:
import os
import gc
import json
import random

import numpy as np
import pandas as pd
import torch

from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoConfig,
    AutoModelForTokenClassification,
    DataCollatorForTokenClassification,
    TrainingArguments,
    Trainer,
    TrainerCallback,
    EarlyStoppingCallback,
    set_seed,
)
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

import optuna

print("Torch      :", torch.__version__)
print("CUDA avail :", torch.cuda.is_available())
print("GPU count  :", torch.cuda.device_count())
for i in range(torch.cuda.device_count()):
    print(" -", torch.cuda.get_device_name(i))

Torch      : 2.10.0+cu128
CUDA avail : True
GPU count  : 2
 - Tesla T4
 - Tesla T4

## 2. Experiment Configuration

Single source of truth for paths and hyperparameter constants — everything downstream reads from here.
A fixed random seed keeps data shuffling, weight init, and training behaviour reproducible.

In [4]:
# ==========================================================
# Paths
# ==========================================================
PROJECT_DIR = "/kaggle/working/indic_llmlingua"
DATASET_PATH = "/kaggle/input/datasets/iitm21f1002300/indic-lingua-data"

CHECKPOINT_DIR = os.path.join(PROJECT_DIR, "checkpoints")
LOG_DIR        = os.path.join(PROJECT_DIR, "logs")
PREDICTION_DIR = os.path.join(PROJECT_DIR, "predictions")
CONFIG_DIR     = os.path.join(PROJECT_DIR, "configs")
TUNING_DIR     = os.path.join(PROJECT_DIR, "optuna_hyperparameter_search")
FINAL_MODEL_DIR = os.path.join(PROJECT_DIR, "final_model")

for directory in [
    PROJECT_DIR, CHECKPOINT_DIR, LOG_DIR,
    PREDICTION_DIR, CONFIG_DIR, TUNING_DIR, FINAL_MODEL_DIR,
]:
    os.makedirs(directory, exist_ok=True)

# ==========================================================
# Model / training constants
# ==========================================================
MODEL_NAME = "FacebookAI/xlm-roberta-base"
MAX_LENGTH = 512
NUM_LABELS = 2
SEED = 42

IGNORE_LABEL = -100

ID2LABEL = {0: "REMOVE", 1: "KEEP"}
LABEL2ID = {"REMOVE": 0, "KEEP": 1}

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def fix_seed(seed: int = SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


fix_seed(SEED)

experiment_config = {
    "model_name": MODEL_NAME,
    "max_length": MAX_LENGTH,
    "num_labels": NUM_LABELS,
    "seed": SEED,
}
with open(os.path.join(CONFIG_DIR, "experiment_config.json"), "w") as fp:
    json.dump(experiment_config, fp, indent=4)

print(f"Device            : {DEVICE}")
print(f"Random seed fixed : {SEED}")
print("Project directories ready.")

Device            : cuda
Random seed fixed : 42
Project directories ready.

## 3. Load Dataset

Token-level binary labels for context compression, stored as JSONL. Each example contains
`question`, `original_answer`, `tokens`, and `labels`.

In [5]:
dataset = load_dataset(
    "json",
    data_files={
        "train": f"{DATASET_PATH}/train.jsonl",
        "validation": f"{DATASET_PATH}/val.jsonl",
        "test": f"{DATASET_PATH}/test.jsonl",
    },
)

print(dataset)

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['question', 'original_answer', 'tokens', 'labels'],
        num_rows: 1609
    })
    validation: Dataset({
        features: ['question', 'original_answer', 'tokens', 'labels'],
        num_rows: 201
    })
    test: Dataset({
        features: ['question', 'original_answer', 'tokens', 'labels'],
        num_rows: 202
    })
})

In [6]:
# Class balance (flattened, ignoring padding/subword-continuation labels)
flat_labels = [
    label
    for sequence in dataset["train"]["labels"]
    for label in sequence
    if label != IGNORE_LABEL
]
class_counts = np.bincount(flat_labels, minlength=2)

print("Train / Validation / Test samples:",
      len(dataset["train"]), "/", len(dataset["validation"]), "/", len(dataset["test"]))
print("Class counts [REMOVE, KEEP]:", class_counts)

Train / Validation / Test samples: 1609 / 201 / 202
Class counts [REMOVE, KEEP]: [523634 143011]

## 4. Tokenizer & Label Alignment

XLM-RoBERTa uses SentencePiece, so a single word may split into multiple subword tokens. Only the
**first** subword of each word keeps its original label; all following subwords (and special /
padding tokens) get `-100` so they're ignored in the loss.

In [7]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
print("Tokenizer loaded:", MODEL_NAME)

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Tokenizer loaded: FacebookAI/xlm-roberta-base

In [8]:
def tokenize_and_align_labels(examples):
    tokenized = tokenizer(
        examples["tokens"],
        is_split_into_words=True,
        truncation=True,
        max_length=MAX_LENGTH,
    )

    aligned_labels = []
    for batch_index in range(len(examples["tokens"])):
        word_ids = tokenized.word_ids(batch_index=batch_index)
        labels = examples["labels"][batch_index]

        previous_word = None
        label_ids = []
        for word_id in word_ids:
            if word_id is None:                       # special / padding tokens
                label_ids.append(IGNORE_LABEL)
            elif word_id != previous_word:              # first subword of a word
                label_ids.append(labels[word_id])
            else:                                        # continuation subwords
                label_ids.append(IGNORE_LABEL)
            previous_word = word_id

        aligned_labels.append(label_ids)

    tokenized["labels"] = aligned_labels
    return tokenized


tokenized_dataset = dataset.map(
    tokenize_and_align_labels,
    batched=True,
    remove_columns=dataset["train"].column_names,
    desc="Tokenizing dataset",
)

tokenized_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

print(tokenized_dataset)

Tokenizing dataset:   0%|          | 0/1609 [00:00<?, ? examples/s]

Tokenizing dataset:   0%|          | 0/201 [00:00<?, ? examples/s]

Tokenizing dataset:   0%|          | 0/202 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 1609
    })
    validation: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 201
    })
    test: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 202
    })
})

## 5. Data Collator & Metrics

Dynamic padding per batch (instead of padding every example to `MAX_LENGTH`) improves GPU
utilization. Labels are padded with `-100` so padded positions never contribute to the loss.

In [9]:
data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer, padding=True)


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    true_predictions, true_labels = [], []
    for pred_seq, label_seq in zip(predictions, labels):
        for pred, label in zip(pred_seq, label_seq):
            if label == IGNORE_LABEL:
                continue
            true_predictions.append(pred)
            true_labels.append(label)

    precision, recall, f1, _ = precision_recall_fscore_support(
        true_labels, true_predictions, average="binary", zero_division=0,
    )
    accuracy = accuracy_score(true_labels, true_predictions)

    return {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}


print("Data collator and compute_metrics ready.")

Data collator and compute_metrics ready.

## 6. Model Builder

A fresh XLM-RoBERTa encoder + randomly-initialized 2-class token classification head
(`0 = REMOVE`, `1 = KEEP`) is instantiated for every trial, so experiments never leak weights
into one another.

In [10]:
def build_model():
    model = AutoModelForTokenClassification.from_pretrained(
        MODEL_NAME,
        num_labels=NUM_LABELS,
        id2label=ID2LABEL,
        label2id=LABEL2ID,
    )
    model.gradient_checkpointing_enable()
    model.to(DEVICE)
    return model


_probe_model = build_model()
total_params = sum(p.numel() for p in _probe_model.parameters())
trainable_params = sum(p.numel() for p in _probe_model.parameters() if p.requires_grad)
print(f"Total parameters     : {total_params:,}")
print(f"Trainable parameters : {trainable_params:,}")

del _probe_model
gc.collect()
torch.cuda.empty_cache()

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Total parameters     : 277,454,594
Trainable parameters : 277,454,594

## 7. Hyperparameter Tuning with Optuna

For every trial, Optuna samples: `learning_rate`, `per_device_train_batch_size`,
`gradient_accumulation_steps`, `weight_decay`, `warmup_ratio`, `num_train_epochs`,
`lr_scheduler_type`, and `max_grad_norm`.

A fresh model is trained on the training split and evaluated on the **validation** split after
every epoch. An `OptunaPruningCallback` reports the running validation F1 back to Optuna after
each epoch and stops the trial early if it's clearly underperforming — this is what actually makes
`MedianPruner` useful (the previous version created a pruner but never called `trial.report`, so
every trial ran to completion regardless of how bad it looked early on).

The best trial's F1 score is returned as the objective to maximize.

In [11]:
class OptunaPruningCallback(TrainerCallback):
    """
    Reports validation F1 to Optuna after each evaluation
    and prunes unpromising trials.
    """

    def __init__(self, trial, metric_name="eval_f1"):
        self.trial = trial
        self.metric_name = metric_name

    def on_evaluate(self, args, state, control, metrics=None, **kwargs):

        if metrics is None:
            return control

        score = metrics.get(self.metric_name)

        if score is None:
            return control

        epoch = int(round(state.epoch or 0))

        self.trial.report(score, step=epoch)

        if self.trial.should_prune():
            raise optuna.TrialPruned(
                f"Trial {self.trial.number} pruned at epoch "
                f"{state.epoch:.1f} (f1={score:.4f})"
            )

        return control


def objective(trial):

    # ==========================================================
    # 1. OPTUNA HYPERPARAMETERS
    # ==========================================================

    learning_rate = trial.suggest_float(
        "learning_rate",
        5e-6,
        5e-5,
        log=True
    )

    batch_size = trial.suggest_categorical(
        "per_device_train_batch_size",
        [8, 16]
    )

    gradient_accumulation_steps = trial.suggest_categorical(
        "gradient_accumulation_steps",
        [1, 2, 4]
    )

    weight_decay = trial.suggest_float(
        "weight_decay",
        1e-4,
        0.1,
        log=True
    )

    warmup_ratio = trial.suggest_float(
        "warmup_ratio",
        0.0,
        0.15
    )

    num_train_epochs = trial.suggest_int(
        "num_train_epochs",
        2,
        6
    )

    lr_scheduler_type = trial.suggest_categorical(
        "lr_scheduler_type",
        [
            "linear",
            "cosine",
            "cosine_with_restarts"
        ]
    )

    max_grad_norm = trial.suggest_float(
        "max_grad_norm",
        0.5,
        2.0
    )


    # ==========================================================
    # 2. PRINT TRIAL CONFIGURATION
    # ==========================================================

    config = {
        "learning_rate": learning_rate,
        "per_device_train_batch_size": batch_size,
        "gradient_accumulation_steps": gradient_accumulation_steps,
        "weight_decay": weight_decay,
        "warmup_ratio": warmup_ratio,
        "num_train_epochs": num_train_epochs,
        "lr_scheduler_type": lr_scheduler_type,
        "max_grad_norm": max_grad_norm,
    }

    print("\n" + "=" * 80)
    print(f"OPTUNA TRIAL {trial.number}")
    print("=" * 80)

    for key, value in config.items():
        print(f"{key}: {value}")

    print("=" * 80)


    # ==========================================================
    # 3. REPRODUCIBILITY
    # ==========================================================

    fix_seed(SEED)


    # ==========================================================
    # 4. TRIAL OUTPUT DIRECTORY
    # ==========================================================

    trial_output_dir = os.path.join(
        TUNING_DIR,
        f"trial_{trial.number}"
    )

    os.makedirs(
        trial_output_dir,
        exist_ok=True
    )


    # ==========================================================
    # 5. TRAINING ARGUMENTS
    # ==========================================================

    training_args = TrainingArguments(

        output_dir=trial_output_dir,

        # -------------------------
        # Training
        # -------------------------
        num_train_epochs=num_train_epochs,

        learning_rate=learning_rate,

        per_device_train_batch_size=batch_size,

        per_device_eval_batch_size=8,

        gradient_accumulation_steps=gradient_accumulation_steps,

        weight_decay=weight_decay,

        warmup_ratio=warmup_ratio,

        lr_scheduler_type=lr_scheduler_type,

        max_grad_norm=max_grad_norm,

        # -------------------------
        # Evaluation
        # -------------------------
        eval_strategy="epoch",

        # Trials are temporary.
        # Final best model will be trained separately.
        save_strategy="no",

        # -------------------------
        # LOGGING
        # -------------------------

        # IMPORTANT:
        # Log training loss once per epoch
        logging_strategy="epoch",

        # IMPORTANT:
        # Show the Trainer progress bar
        disable_tqdm=False,

        # -------------------------
        # Best metric
        # -------------------------

        metric_for_best_model="f1",

        greater_is_better=True,

        # -------------------------
        # Performance
        # -------------------------

        fp16=torch.cuda.is_available(),

        # -------------------------
        # Reproducibility
        # -------------------------

        seed=SEED,

        # -------------------------
        # Disable external logging
        # -------------------------

        report_to="none",
    )


    # ==========================================================
    # 6. CREATE FRESH MODEL
    # ==========================================================

    model = build_model()


    # ==========================================================
    # 7. CREATE TRAINER
    # ==========================================================

    trainer = Trainer(

        model=model,

        args=training_args,

        train_dataset=tokenized_dataset["train"],

        eval_dataset=tokenized_dataset["validation"],

        processing_class=tokenizer,

        data_collator=data_collator,

        compute_metrics=compute_metrics,

        callbacks=[
            OptunaPruningCallback(trial),

            EarlyStoppingCallback(
                early_stopping_patience=2,
                early_stopping_threshold=0.0
            ),
        ],
    )


    # ==========================================================
    # 8. TRAIN TRIAL
    # ==========================================================

    try:

        trainer.train()


        # ======================================================
        # 9. FINAL EVALUATION OF THIS TRIAL
        # ======================================================

        metrics = trainer.evaluate()


        # ======================================================
        # 10. EXTRACT BEST F1
        # ======================================================

        f1 = metrics.get("eval_f1")

        if f1 is None:
            raise ValueError(
                "eval_f1 was not found in evaluation metrics."
            )


        # ======================================================
        # 11. STORE OPTUNA USER ATTRIBUTES
        # ======================================================

        trial.set_user_attr(
            "eval_accuracy",
            metrics.get("eval_accuracy")
        )

        trial.set_user_attr(
            "eval_precision",
            metrics.get("eval_precision")
        )

        trial.set_user_attr(
            "eval_recall",
            metrics.get("eval_recall")
        )

        trial.set_user_attr(
            "eval_loss",
            metrics.get("eval_loss")
        )


        # ======================================================
        # 12. CREATE EPOCH-WISE TRAINING TABLE
        # ======================================================

        history = trainer.state.log_history

        training_logs = [
            log for log in history
            if "loss" in log and "eval_loss" not in log
        ]

        evaluation_logs = [
            log for log in history
            if "eval_loss" in log
        ]


        epoch_results = []

        for eval_log in evaluation_logs:

            epoch = eval_log.get("epoch")

            if epoch is None:
                continue

            # Find training log corresponding to this epoch
            matching_train_logs = [
                log for log in training_logs
                if log.get("epoch") is not None
                and abs(
                    float(log["epoch"]) - float(epoch)
                ) < 0.01
            ]

            train_loss = None

            if matching_train_logs:
                train_loss = matching_train_logs[-1].get("loss")


            epoch_results.append({

                "Epoch": int(round(epoch)),

                "Training Loss": train_loss,

                "Validation Loss": eval_log.get(
                    "eval_loss"
                ),

                "Accuracy": eval_log.get(
                    "eval_accuracy"
                ),

                "Precision": eval_log.get(
                    "eval_precision"
                ),

                "Recall": eval_log.get(
                    "eval_recall"
                ),

                "F1": eval_log.get(
                    "eval_f1"
                ),
            })


        # ======================================================
        # 13. DISPLAY EPOCH-WISE RESULTS
        # ======================================================

        if epoch_results:

            history_df = pd.DataFrame(
                epoch_results
            )

            print("\n")
            print(history_df.to_string(index=False))

        else:

            print(
                "\nWarning: No epoch-wise training "
                "history was found."
            )


        # ======================================================
        # 14. DISPLAY FINAL TRIAL METRICS
        # ======================================================

        print("\n" + "-" * 80)
        print(f"TRIAL {trial.number} COMPLETED")
        print("-" * 80)

        print(
            f"Validation Loss : "
            f"{metrics.get('eval_loss', float('nan')):.6f}"
        )

        print(
            f"Accuracy        : "
            f"{metrics.get('eval_accuracy', float('nan')):.6f}"
        )

        print(
            f"Precision       : "
            f"{metrics.get('eval_precision', float('nan')):.6f}"
        )

        print(
            f"Recall          : "
            f"{metrics.get('eval_recall', float('nan')):.6f}"
        )

        print(
            f"F1              : "
            f"{f1:.6f}"
        )

        print("-" * 80)


        # ======================================================
        # 15. RETURN OPTUNA OBJECTIVE
        # ======================================================

        return f1


    except optuna.TrialPruned:

        print(
            f"\nTrial {trial.number} was pruned."
        )

        raise


    except Exception as exc:

        print(
            f"\nTrial {trial.number} failed:"
        )

        print(exc)

        raise


    finally:

        # ======================================================
        # 16. GPU MEMORY CLEANUP
        # ======================================================

        del trainer
        del model

        gc.collect()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

In [12]:
N_TRIALS = 30          # lower this (e.g. 10-15) for a quicker search
TIMEOUT_SECONDS = 36000  # e.g. 6 * 3600 to hard-cap the search to 6 hours

study = optuna.create_study(
    study_name="xlmr_prompt_compression",
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=SEED),
    pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=1),
)

study.optimize(
    objective,
    n_trials=N_TRIALS,
    timeout=TIMEOUT_SECONDS,
    gc_after_trial=True,
)

[I 2026-08-25 18:26:07,003] A new study created in memory with name: xlmr_prompt_compression
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 0
================================================================================
learning_rate: 1.1844319751820392e-05
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
weight_decay: 0.00014936568554617635
warmup_ratio: 0.12992642186624026
num_train_epochs: 5
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 1.7486639612006325
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/tmp/ipykernel_24/2238381067.py:23: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  self.trial.report(score, step=epoch)

 Epoch  Training Loss  Validation Loss  Accuracy  Precision   Recall       F1
     1       1.041590         0.931387  0.729806   0.548956 0.264860 0.357320
     2       0.889549         0.933204  0.736040   0.664210 0.139997 0.231252
     3       0.863532         0.906671  0.750579   0.606230 0.343806 0.438774
     4       0.826058         0.924241  0.748801   0.582881 0.401634 0.475574
     5       0.798424         0.922802  0.742975   0.545343 0.563324 0.554188
     5       0.798424         0.922802  0.742975   0.545343 0.563324 0.554188

--------------------------------------------------------------------------------
TRIAL 0 COMPLETED
--------------------------------------------------------------------------------
Validation Loss : 0.922802
Accuracy        : 0.742975
Precision       : 0.545343
Recall          : 0.563324
F1              : 0.554188
--------------------------------------------------------------------------------

[I 2026-08-25 18:37:27,423] Trial 0 finished with value: 0.5541875406866491 and parameters: {'learning_rate': 1.1844319751820392e-05, 'per_device_train_batch_size': 8, 'gradient_accumulation_steps': 1, 'weight_decay': 0.00014936568554617635, 'warmup_ratio': 0.12992642186624026, 'num_train_epochs': 5, 'lr_scheduler_type': 'cosine_with_restarts', 'max_grad_norm': 1.7486639612006325}. Best is trial 0 with value: 0.5541875406866491.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 1
================================================================================
learning_rate: 8.152843673110734e-06
per_device_train_batch_size: 16
gradient_accumulation_steps: 2
weight_decay: 0.0007476312062252305
warmup_ratio: 0.09177793420835692
num_train_epochs: 2
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 1.6777639420895203
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/tmp/ipykernel_24/2238381067.py:23: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  self.trial.report(score, step=epoch)
[I 2026-08-25 18:41:36,589] Trial 1 finished with value: 0.09949374935427213 and parameters: {'learning_rate': 8.152843673110734e-06, 'per_device_train_batch_size': 16, 'gradient_accumulation_steps': 2, 'weight_decay': 0.0007476312062252305, 'warmup_ratio': 0.09177793420835692, 'num_train_epochs': 2, 'lr_scheduler_type': 'cosine_with_restarts', 'max_grad_norm': 1.6777639420895203}. Best is trial 0 with value: 0.5541875406866491.

 Epoch  Training Loss  Validation Loss  Accuracy  Precision   Recall       F1
     1       2.236337         1.025721  0.716409   0.000000 0.000000 0.000000
     2       1.814281         0.958112  0.715545   0.486609 0.055412 0.099494
     2       1.814281         0.958112  0.715545   0.486609 0.055412 0.099494

--------------------------------------------------------------------------------
TRIAL 1 COMPLETED
--------------------------------------------------------------------------------
Validation Loss : 0.958112
Accuracy        : 0.715545
Precision       : 0.486609
Recall          : 0.055412
F1              : 0.099494
--------------------------------------------------------------------------------

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 2
================================================================================
learning_rate: 7.91851577955937e-06
per_device_train_batch_size: 16
gradient_accumulation_steps: 2
weight_decay: 0.00015673095467235422
warmup_ratio: 0.14233283058799998
num_train_epochs: 6
lr_scheduler_type: linear
max_grad_norm: 1.5263495397682354
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/tmp/ipykernel_24/2238381067.py:23: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  self.trial.report(score, step=epoch)
[I 2026-08-25 18:53:51,559] Trial 2 finished with value: 0.42447824548991864 and parameters: {'learning_rate': 7.91851577955937e-06, 'per_device_train_batch_size': 16, 'gradient_accumulation_steps': 2, 'weight_decay': 0.00015673095467235422, 'warmup_ratio': 0.14233283058799998, 'num_train_epochs': 6, 'lr_scheduler_type': 'linear', 'max_grad_norm': 1.5263495397682354}. Best is trial 0 with value: 0.5541875406866491.

 Epoch  Training Loss  Validation Loss  Accuracy  Precision   Recall       F1
     1       2.336313         1.100236  0.716409   0.000000 0.000000 0.000000
     2       1.855196         0.937323  0.717503   0.504253 0.228552 0.314539
     3       1.769265         0.939459  0.719477   0.560724 0.049945 0.091721
     4       1.742685         0.935808  0.729725   0.545607 0.280856 0.370826
     5       1.719643         0.926177  0.732891   0.538798 0.403533 0.461457
     6       1.722829         0.934069  0.734506   0.550914 0.345244 0.424478
     6       1.722829         0.934069  0.734506   0.550914 0.345244 0.424478

--------------------------------------------------------------------------------
TRIAL 2 COMPLETED
--------------------------------------------------------------------------------
Validation Loss : 0.934069
Accuracy        : 0.734506
Precision       : 0.550914
Recall          : 0.345244
F1              : 0.424478
--------------------------------------------------------------------------------

================================================================================
OPTUNA TRIAL 3
================================================================================
learning_rate: 1.3775979824755385e-05
per_device_train_batch_size: 16
gradient_accumulation_steps: 2
weight_decay: 0.009717775305059635
warmup_ratio: 0.04675666141341164
num_train_epochs: 4
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 1.6626992350416718
================================================================================

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/tmp/ipykernel_24/2238381067.py:23: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  self.trial.report(score, step=epoch)

 Epoch  Training Loss  Validation Loss  Accuracy  Precision   Recall       F1
     1       2.106501         0.948931  0.709850   0.486844 0.427988 0.455523
     2       1.765902         0.942820  0.719657   0.566823 0.048564 0.089464
     3       1.748664         0.934879  0.725809   0.572144 0.131423 0.213748
     3       1.748664         0.934879  0.725809   0.572144 0.131423 0.213748

--------------------------------------------------------------------------------
TRIAL 3 COMPLETED
--------------------------------------------------------------------------------
Validation Loss : 0.934879
Accuracy        : 0.725809
Precision       : 0.572144
Recall          : 0.131423
F1              : 0.213748
--------------------------------------------------------------------------------

[I 2026-08-25 19:00:02,543] Trial 3 finished with value: 0.21374760189041225 and parameters: {'learning_rate': 1.3775979824755385e-05, 'per_device_train_batch_size': 16, 'gradient_accumulation_steps': 2, 'weight_decay': 0.009717775305059635, 'warmup_ratio': 0.04675666141341164, 'num_train_epochs': 4, 'lr_scheduler_type': 'cosine_with_restarts', 'max_grad_norm': 1.6626992350416718}. Best is trial 0 with value: 0.5541875406866491.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 4
================================================================================
learning_rate: 4.3497965642566594e-05
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
weight_decay: 0.0001366727291545623
warmup_ratio: 0.04879954961448965
num_train_epochs: 3
lr_scheduler_type: cosine
max_grad_norm: 0.9214017645310711
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/tmp/ipykernel_24/2238381067.py:23: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  self.trial.report(score, step=epoch)
[I 2026-08-25 19:06:52,584] Trial 4 finished with value: 0.4750741131972604 and parameters: {'learning_rate': 4.3497965642566594e-05, 'per_device_train_batch_size': 8, 'gradient_accumulation_steps': 1, 'weight_decay': 0.0001366727291545623, 'warmup_ratio': 0.04879954961448965, 'num_train_epochs': 3, 'lr_scheduler_type': 'cosine', 'max_grad_norm': 0.9214017645310711}. Best is trial 0 with value: 0.5541875406866491.

 Epoch  Training Loss  Validation Loss  Accuracy  Precision   Recall       F1
     1       0.993649         1.015312  0.737541   0.596830 0.229645 0.331671
     2       0.897685         0.934776  0.748507   0.610419 0.312849 0.413680
     3       0.871292         0.946721  0.748621   0.582470 0.401116 0.475074
     3       0.871292         0.946721  0.748621   0.582470 0.401116 0.475074

--------------------------------------------------------------------------------
TRIAL 4 COMPLETED
--------------------------------------------------------------------------------
Validation Loss : 0.946721
Accuracy        : 0.748621
Precision       : 0.582470
Recall          : 0.401116
F1              : 0.475074
--------------------------------------------------------------------------------

================================================================================
OPTUNA TRIAL 5
================================================================================
learning_rate: 1.744480372569611e-05
per_device_train_batch_size: 16
gradient_accumulation_steps: 2
weight_decay: 0.00039459088111000007
warmup_ratio: 0.0008283175685403598
num_train_epochs: 6
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 0.6110669776011355
================================================================================

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 19:08:55,543] Trial 5 pruned. Trial 5 pruned at epoch 1.0 (f1=0.0546)

Trial 5 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 6
================================================================================
learning_rate: 1.1413943879952556e-05
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
weight_decay: 0.0008569331925053991
warmup_ratio: 0.048777498304012054
num_train_epochs: 5
lr_scheduler_type: cosine
max_grad_norm: 0.6793913689074526
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 19:11:00,269] Trial 6 pruned. Trial 6 pruned at epoch 1.0 (f1=0.0940)

Trial 6 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 7
================================================================================
learning_rate: 2.5835376300116388e-05
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
weight_decay: 0.0019170041589170674
warmup_ratio: 0.003812869011614278
num_train_epochs: 2
lr_scheduler_type: cosine
max_grad_norm: 1.262856036747054
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 19:13:16,862] Trial 7 pruned. Trial 7 pruned at epoch 1.0 (f1=0.1042)

Trial 7 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 8
================================================================================
learning_rate: 4.041443189081017e-05
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
weight_decay: 0.0007400385759087378
warmup_ratio: 0.02418319308810066
num_train_epochs: 6
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 1.7055081153486717
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 19:15:21,583] Trial 8 pruned. Trial 8 pruned at epoch 1.0 (f1=0.2755)

Trial 8 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 9
================================================================================
learning_rate: 7.683163288062507e-06
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
weight_decay: 0.0002138729075414894
warmup_ratio: 0.03419027438129125
num_train_epochs: 4
lr_scheduler_type: cosine
max_grad_norm: 1.2661209538663485
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/tmp/ipykernel_24/2238381067.py:23: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  self.trial.report(score, step=epoch)
[I 2026-08-25 19:24:15,506] Trial 9 finished with value: 0.5223751156336726 and parameters: {'learning_rate': 7.683163288062507e-06, 'per_device_train_batch_size': 8, 'gradient_accumulation_steps': 2, 'weight_decay': 0.0002138729075414894, 'warmup_ratio': 0.03419027438129125, 'num_train_epochs': 4, 'lr_scheduler_type': 'cosine', 'max_grad_norm': 1.2661209538663485}. Best is trial 0 with value: 0.5541875406866491.

 Epoch  Training Loss  Validation Loss  Accuracy  Precision   Recall       F1
     1       2.065190         0.936412  0.717372   0.502526 0.337706 0.403951
     2       1.787069         0.941055  0.722317   0.560013 0.097186 0.165629
     3       1.754832         0.932675  0.731814   0.536944 0.394729 0.454983
     4       1.734615         0.931070  0.730394   0.524894 0.519880 0.522375
     4       1.734615         0.931070  0.730394   0.524894 0.519880 0.522375

--------------------------------------------------------------------------------
TRIAL 9 COMPLETED
--------------------------------------------------------------------------------
Validation Loss : 0.931070
Accuracy        : 0.730394
Precision       : 0.524894
Recall          : 0.519880
F1              : 0.522375
--------------------------------------------------------------------------------

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 10
================================================================================
learning_rate: 5.431471452151295e-06
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
weight_decay: 0.06264278041381323
warmup_ratio: 0.14642465979271543
num_train_epochs: 4
lr_scheduler_type: linear
max_grad_norm: 1.9480043551361126
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 19:26:27,387] Trial 10 pruned. Trial 10 pruned at epoch 1.0 (f1=0.0000)

Trial 10 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 11
================================================================================
learning_rate: 8.485161061049303e-06
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
weight_decay: 0.00010389213999349096
warmup_ratio: 0.1053251604037724
num_train_epochs: 4
lr_scheduler_type: cosine
max_grad_norm: 1.134300069484857
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 19:28:39,367] Trial 11 pruned. Trial 11 pruned at epoch 1.0 (f1=0.0000)

Trial 11 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 12
================================================================================
learning_rate: 5.35265776353952e-06
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
weight_decay: 0.003247867057519732
warmup_ratio: 0.09457666360106148
num_train_epochs: 5
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 1.36021823933615
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/tmp/ipykernel_24/2238381067.py:23: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  self.trial.report(score, step=epoch)
[I 2026-08-25 19:40:00,037] Trial 12 finished with value: 0.5043596142588656 and parameters: {'learning_rate': 5.35265776353952e-06, 'per_device_train_batch_size': 8, 'gradient_accumulation_steps': 1, 'weight_decay': 0.003247867057519732, 'warmup_ratio': 0.09457666360106148, 'num_train_epochs': 5, 'lr_scheduler_type': 'cosine_with_restarts', 'max_grad_norm': 1.36021823933615}. Best is trial 0 with value: 0.5541875406866491.

 Epoch  Training Loss  Validation Loss  Accuracy  Precision   Recall       F1
     1       1.057883         0.941615  0.716197   0.499524 0.392428 0.439546
     2       0.899311         0.938033  0.722414   0.591908 0.068186 0.122285
     3       0.875167         0.919674  0.734996   0.535897 0.489211 0.511491
     4       0.861669         0.929346  0.740070   0.562083 0.377697 0.451802
     5       0.853153         0.925258  0.737492   0.542844 0.470971 0.504360
     5       0.853153         0.925258  0.737492   0.542844 0.470971 0.504360

--------------------------------------------------------------------------------
TRIAL 12 COMPLETED
--------------------------------------------------------------------------------
Validation Loss : 0.925258
Accuracy        : 0.737492
Precision       : 0.542844
Recall          : 0.470971
F1              : 0.504360
--------------------------------------------------------------------------------

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 13
================================================================================
learning_rate: 2.1213530344635444e-05
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
weight_decay: 0.00021621924769710976
warmup_ratio: 0.12137741451339701
num_train_epochs: 5
lr_scheduler_type: cosine
max_grad_norm: 1.906252164748084
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 19:42:13,955] Trial 13 pruned. Trial 13 pruned at epoch 1.0 (f1=0.0237)

Trial 13 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 14
================================================================================
learning_rate: 1.1184236441426344e-05
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
weight_decay: 0.00036966934448181746
warmup_ratio: 0.06344476711963758
num_train_epochs: 3
lr_scheduler_type: linear
max_grad_norm: 1.0411130318161874
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 19:44:26,334] Trial 14 pruned. Trial 14 pruned at epoch 1.0 (f1=0.0774)

Trial 14 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 15
================================================================================
learning_rate: 6.942611590070028e-06
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
weight_decay: 0.002543874639381168
warmup_ratio: 0.0741667179579247
num_train_epochs: 5
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 1.380228198832686
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/tmp/ipykernel_24/2238381067.py:23: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  self.trial.report(score, step=epoch)

 Epoch  Training Loss  Validation Loss  Accuracy  Precision   Recall       F1
     1       2.133631         0.946227  0.711367   0.490837 0.476207 0.483411
     2       1.792873         0.940313  0.720424   0.543555 0.088325 0.151958
     3       1.770343         0.930366  0.730524   0.526581 0.493009 0.509242
     4       1.738016         0.932808  0.735714   0.545707 0.406352 0.465831
     5       1.723741         0.931885  0.734979   0.542686 0.416249 0.471132
     5       1.723741         0.931885  0.734979   0.542686 0.416249 0.471132

--------------------------------------------------------------------------------
TRIAL 15 COMPLETED
--------------------------------------------------------------------------------
Validation Loss : 0.931885
Accuracy        : 0.734979
Precision       : 0.542686
Recall          : 0.416249
F1              : 0.471132
--------------------------------------------------------------------------------

[I 2026-08-25 19:55:31,763] Trial 15 finished with value: 0.471132241362467 and parameters: {'learning_rate': 6.942611590070028e-06, 'per_device_train_batch_size': 8, 'gradient_accumulation_steps': 2, 'weight_decay': 0.002543874639381168, 'warmup_ratio': 0.0741667179579247, 'num_train_epochs': 5, 'lr_scheduler_type': 'cosine_with_restarts', 'max_grad_norm': 1.380228198832686}. Best is trial 0 with value: 0.5541875406866491.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 16
================================================================================
learning_rate: 1.1486112822115804e-05
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
weight_decay: 0.00031520050057831157
warmup_ratio: 0.1239652199039595
num_train_epochs: 3
lr_scheduler_type: cosine
max_grad_norm: 0.9118548917173037
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 19:57:48,998] Trial 16 pruned. Trial 16 pruned at epoch 1.0 (f1=0.0882)

Trial 16 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 17
================================================================================
learning_rate: 1.5264612277621275e-05
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
weight_decay: 0.06924920297434978
warmup_ratio: 0.029812980644194
num_train_epochs: 4
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 1.5046563853746542
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 20:00:02,889] Trial 17 pruned. Trial 17 pruned at epoch 1.0 (f1=0.0516)

Trial 17 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 18
================================================================================
learning_rate: 2.6059418034312535e-05
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
weight_decay: 0.007575943736130873
warmup_ratio: 0.07230516787254619
num_train_epochs: 5
lr_scheduler_type: cosine
max_grad_norm: 1.8177547362544662
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 20:02:19,899] Trial 18 pruned. Trial 18 pruned at epoch 1.0 (f1=0.0175)

Trial 18 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 19
================================================================================
learning_rate: 9.831171848677025e-06
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
weight_decay: 0.00010017208529113676
warmup_ratio: 0.12311378788473464
num_train_epochs: 4
lr_scheduler_type: linear
max_grad_norm: 0.7873371768711221
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 20:04:32,191] Trial 19 pruned. Trial 19 pruned at epoch 1.0 (f1=0.0000)

Trial 19 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 20
================================================================================
learning_rate: 6.328015125425728e-06
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
weight_decay: 0.0013264013202921457
warmup_ratio: 0.02578645291470978
num_train_epochs: 3
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 1.219029766085364
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 20:06:45,999] Trial 20 pruned. Trial 20 pruned at epoch 1.0 (f1=0.3571)

Trial 20 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 21
================================================================================
learning_rate: 5.205352647695101e-06
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
weight_decay: 0.004637044862432577
warmup_ratio: 0.10702110681176039
num_train_epochs: 5
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 1.3523610311781382
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 20:09:02,722] Trial 21 pruned. Trial 21 pruned at epoch 1.0 (f1=0.3507)

Trial 21 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 22
================================================================================
learning_rate: 6.148135989504233e-06
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
weight_decay: 0.021168244226565564
warmup_ratio: 0.08837285439447845
num_train_epochs: 5
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 1.4476160194070824
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/tmp/ipykernel_24/2238381067.py:23: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  self.trial.report(score, step=epoch)

 Epoch  Training Loss  Validation Loss  Accuracy  Precision   Recall       F1
     1       1.046969         0.934752  0.720913   0.512482 0.326026 0.398523
     2       0.895999         0.940345  0.727277   0.603998 0.111284 0.187940
     3       0.871867         0.919256  0.740723   0.550495 0.467346 0.505524
     4       0.854982         0.932871  0.744444   0.583903 0.343978 0.432922
     5       0.842855         0.926489  0.739385   0.543797 0.502963 0.522584
     5       0.842855         0.926489  0.739385   0.543797 0.502963 0.522584

--------------------------------------------------------------------------------
TRIAL 22 COMPLETED
--------------------------------------------------------------------------------
Validation Loss : 0.926489
Accuracy        : 0.739385
Precision       : 0.543797
Recall          : 0.502963
F1              : 0.522584
--------------------------------------------------------------------------------

[I 2026-08-25 20:20:23,002] Trial 22 finished with value: 0.5225839237138672 and parameters: {'learning_rate': 6.148135989504233e-06, 'per_device_train_batch_size': 8, 'gradient_accumulation_steps': 1, 'weight_decay': 0.021168244226565564, 'warmup_ratio': 0.08837285439447845, 'num_train_epochs': 5, 'lr_scheduler_type': 'cosine_with_restarts', 'max_grad_norm': 1.4476160194070824}. Best is trial 0 with value: 0.5541875406866491.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 23
================================================================================
learning_rate: 6.766419531131963e-06
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
weight_decay: 0.029201726846562515
warmup_ratio: 0.08812191595071053
num_train_epochs: 6
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 1.5873955976321066
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 20:22:39,946] Trial 23 pruned. Trial 23 pruned at epoch 1.0 (f1=0.3915)

Trial 23 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 24
================================================================================
learning_rate: 9.414420213877014e-06
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
weight_decay: 0.015319954971517055
warmup_ratio: 0.13070834009379345
num_train_epochs: 4
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 1.4892689898187546
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 20:24:56,920] Trial 24 pruned. Trial 24 pruned at epoch 1.0 (f1=0.3741)

Trial 24 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 25
================================================================================
learning_rate: 6.568991779299654e-06
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
weight_decay: 0.03484793451119598
warmup_ratio: 0.11359721492150412
num_train_epochs: 5
lr_scheduler_type: cosine
max_grad_norm: 1.8277567762212428
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/tmp/ipykernel_24/2238381067.py:23: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  self.trial.report(score, step=epoch)
[I 2026-08-25 20:36:17,942] Trial 25 finished with value: 0.5063948100092679 and parameters: {'learning_rate': 6.568991779299654e-06, 'per_device_train_batch_size': 8, 'gradient_accumulation_steps': 1, 'weight_decay': 0.03484793451119598, 'warmup_ratio': 0.11359721492150412, 'num_train_epochs': 5, 'lr_scheduler_type': 'cosine', 'max_grad_norm': 1.8277567762212428}. Best is trial 0 with value: 0.5541875406866491.

 Epoch  Training Loss  Validation Loss  Accuracy  Precision   Recall       F1
     1       1.054467         0.938026  0.719657   0.508688 0.335232 0.404134
     2       0.898154         0.938094  0.723965   0.609664 0.074055 0.132068
     3       0.873130         0.917379  0.739956   0.550878 0.449508 0.495057
     4       0.855550         0.932368  0.741686   0.572922 0.350135 0.434643
     5       0.844255         0.925566  0.739271   0.546728 0.471604 0.506395
     5       0.844255         0.925566  0.739271   0.546728 0.471604 0.506395

--------------------------------------------------------------------------------
TRIAL 25 COMPLETED
--------------------------------------------------------------------------------
Validation Loss : 0.925566
Accuracy        : 0.739271
Precision       : 0.546728
Recall          : 0.471604
F1              : 0.506395
--------------------------------------------------------------------------------

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 26
================================================================================
learning_rate: 1.2914448700068192e-05
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
weight_decay: 0.0002891990960550633
warmup_ratio: 0.13717470713207447
num_train_epochs: 5
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 1.0496783514915655
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 20:38:34,483] Trial 26 pruned. Trial 26 pruned at epoch 1.0 (f1=0.3128)

Trial 26 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 27
================================================================================
learning_rate: 9.70276233292279e-06
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
weight_decay: 0.00046015020287521445
warmup_ratio: 0.07965994716797231
num_train_epochs: 4
lr_scheduler_type: cosine_with_restarts
max_grad_norm: 1.429342890657024
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 20:40:50,946] Trial 27 pruned. Trial 27 pruned at epoch 1.0 (f1=0.0869)

Trial 27 was pruned.

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 28
================================================================================
learning_rate: 1.756138000667427e-05
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
weight_decay: 0.00019469896119821562
warmup_ratio: 0.06396158563743709
num_train_epochs: 6
lr_scheduler_type: linear
max_grad_norm: 1.2600502034886065
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/tmp/ipykernel_24/2238381067.py:23: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  self.trial.report(score, step=epoch)
[I 2026-08-25 20:47:28,290] Trial 28 finished with value: 0.5472187032131751 and parameters: {'learning_rate': 1.756138000667427e-05, 'per_device_train_batch_size': 8, 'gradient_accumulation_steps': 4, 'weight_decay': 0.00019469896119821562, 'warmup_ratio': 0.06396158563743709, 'num_train_epochs': 6, 'lr_scheduler_type': 'linear', 'max_grad_norm': 1.2600502034886065}. Best is trial 0 with value: 0.5541875406866491.

 Epoch  Training Loss  Validation Loss  Accuracy  Precision   Recall       F1
     1       4.187751         0.957189  0.708675   0.489449 0.632603 0.551894
     2       3.519855         0.936979  0.719102   0.573991 0.036826 0.069212
     3       3.475626         0.926150  0.743383   0.547629 0.546809 0.547219
     3       3.475626         0.926150  0.743383   0.547629 0.546809 0.547219

--------------------------------------------------------------------------------
TRIAL 28 COMPLETED
--------------------------------------------------------------------------------
Validation Loss : 0.926150
Accuracy        : 0.743383
Precision       : 0.547629
Recall          : 0.546809
F1              : 0.547219
--------------------------------------------------------------------------------

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

================================================================================
OPTUNA TRIAL 29
================================================================================
learning_rate: 1.8602431364443374e-05
per_device_train_batch_size: 16
gradient_accumulation_steps: 4
weight_decay: 0.0006619892690632929
warmup_ratio: 0.06384525886303134
num_train_epochs: 6
lr_scheduler_type: linear
max_grad_norm: 1.709333555896753
================================================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

[I 2026-08-25 20:49:30,151] Trial 29 pruned. Trial 29 pruned at epoch 1.0 (f1=0.0000)

Trial 29 was pruned.

In [13]:
print("\n" + "=" * 80)
print("BEST TRIAL")
print("=" * 80)
print(f"Trial number : {study.best_trial.number}")
print(f"Best val F1   : {study.best_value}")
print("\nBest hyperparameters:")
for key, value in study.best_params.items():
    print(f"  {key}: {value}")

BEST_PARAMS = study.best_params

================================================================================
BEST TRIAL
================================================================================
Trial number : 0
Best val F1   : 0.5541875406866491

Best hyperparameters:
  learning_rate: 1.1844319751820392e-05
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 1
  weight_decay: 0.00014936568554617635
  warmup_ratio: 0.12992642186624026
  num_train_epochs: 5
  lr_scheduler_type: cosine_with_restarts
  max_grad_norm: 1.7486639612006325

### Saving Optuna results

In [14]:
df_trials = study.trials_dataframe()
df_trials.to_csv(os.path.join(TUNING_DIR, "optuna_trials.csv"), index=False)

with open(os.path.join(CONFIG_DIR, "best_hyperparameters.json"), "w") as fp:
    json.dump(BEST_PARAMS, fp, indent=4)

print(f"Saved {len(df_trials)} trial(s) to {os.path.join(TUNING_DIR, 'optuna_trials.csv')}")
print(f"Saved best hyperparameters to {os.path.join(CONFIG_DIR, 'best_hyperparameters.json')}")

Saved 30 trial(s) to /kaggle/working/indic_llmlingua/optuna_hyperparameter_search/optuna_trials.csv
Saved best hyperparameters to /kaggle/working/indic_llmlingua/configs/best_hyperparameters.json

## 8. Final Training Using the Best Hyperparameters

Retrains a fresh model on the full training split using `study.best_params`, this time with
checkpointing enabled (`save_strategy="epoch"`, `load_best_model_at_end=True`) so the
best-on-validation checkpoint is automatically restored at the end of training.

In [15]:
fix_seed(SEED)

final_training_args = TrainingArguments(
    output_dir=CHECKPOINT_DIR,

    num_train_epochs=BEST_PARAMS["num_train_epochs"],
    learning_rate=BEST_PARAMS["learning_rate"],
    per_device_train_batch_size=BEST_PARAMS["per_device_train_batch_size"],
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=BEST_PARAMS["gradient_accumulation_steps"],
    weight_decay=BEST_PARAMS["weight_decay"],
    warmup_ratio=BEST_PARAMS["warmup_ratio"],
    lr_scheduler_type=BEST_PARAMS["lr_scheduler_type"],
    max_grad_norm=BEST_PARAMS["max_grad_norm"],

    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,

    logging_strategy="steps",
    logging_steps=20,

    fp16=torch.cuda.is_available(),
    report_to="none",
    seed=SEED,
)

final_model = build_model()

final_trainer = Trainer(
    model=final_model,
    args=final_training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3, early_stopping_threshold=0.0)],
)

final_trainer.train()

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=505, training_loss=0.8844920715483109, metrics={'train_runtime': 709.0412, 'train_samples_per_second': 11.346, 'train_steps_per_second': 0.712, 'total_flos': 2102132407941120.0, 'train_loss': 0.8844920715483109, 'epoch': 5.0})

## 9. Evaluate the Best Model on the Validation Set

In [16]:
val_metrics = final_trainer.evaluate(tokenized_dataset["validation"])

print("\n" + "=" * 80)
print("FINAL MODEL — VALIDATION METRICS")
print("=" * 80)
for key, value in val_metrics.items():
    print(f"{key}: {value}")

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

================================================================================
FINAL MODEL — VALIDATION METRICS
================================================================================
eval_loss: 0.9195170998573303
eval_accuracy: 0.7453412094905518
eval_precision: 0.5513942837265928
eval_recall: 0.5472696933080154
eval_f1: 0.549324246274691
eval_runtime: 4.5285
eval_samples_per_second: 44.385
eval_steps_per_second: 2.871
epoch: 5.0

## 10. Save the Final Model & Artifacts

In [17]:
final_trainer.save_model(FINAL_MODEL_DIR)
tokenizer.save_pretrained(FINAL_MODEL_DIR)

with open(os.path.join(FINAL_MODEL_DIR, "validation_metrics.json"), "w") as fp:
    json.dump(val_metrics, fp, indent=4)

with open(os.path.join(FINAL_MODEL_DIR, "best_hyperparameters.json"), "w") as fp:
    json.dump(BEST_PARAMS, fp, indent=4)

history_df = pd.DataFrame(final_trainer.state.log_history)
history_df.to_csv(os.path.join(FINAL_MODEL_DIR, "training_history.csv"), index=False)

print(f"Final model, tokenizer, metrics and training history saved to: {FINAL_MODEL_DIR}")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Final model, tokenizer, metrics and training history saved to: /kaggle/working/indic_llmlingua/final_model